//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Member.XML {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="XML.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addMember", ReplyAction="http://tempuri.org/IService1/addMemberResponse")]
        System.Xml.Linq.XElement addMember(string username, string password, System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addMember", ReplyAction="http://tempuri.org/IService1/addMemberResponse")]
        System.Threading.Tasks.Task<System.Xml.Linq.XElement> addMemberAsync(string username, string password, System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        bool verification(string username, string password, System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/verification", ReplyAction="http://tempuri.org/IService1/verificationResponse")]
        System.Threading.Tasks.Task<bool> verificationAsync(string username, string password, System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMember", ReplyAction="http://tempuri.org/IService1/searchMemberResponse")]
        bool searchMember(string username, System.Xml.Linq.XElement xml);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/searchMember", ReplyAction="http://tempuri.org/IService1/searchMemberResponse")]
        System.Threading.Tasks.Task<bool> searchMemberAsync(string username, System.Xml.Linq.XElement xml);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Member.XML.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Member.XML.IService1>, Member.XML.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Xml.Linq.XElement addMember(string username, string password, System.Xml.Linq.XElement xml) {
            return base.Channel.addMember(username, password, xml);
        }
        
        public System.Threading.Tasks.Task<System.Xml.Linq.XElement> addMemberAsync(string username, string password, System.Xml.Linq.XElement xml) {
            return base.Channel.addMemberAsync(username, password, xml);
        }
        
        public bool verification(string username, string password, System.Xml.Linq.XElement xml) {
            return base.Channel.verification(username, password, xml);
        }
        
        public System.Threading.Tasks.Task<bool> verificationAsync(string username, string password, System.Xml.Linq.XElement xml) {
            return base.Channel.verificationAsync(username, password, xml);
        }
        
        public bool searchMember(string username, System.Xml.Linq.XElement xml) {
            return base.Channel.searchMember(username, xml);
        }
        
        public System.Threading.Tasks.Task<bool> searchMemberAsync(string username, System.Xml.Linq.XElement xml) {
            return base.Channel.searchMemberAsync(username, xml);
        }
    }
}
